use serde::{Serialize, Deserialize};
use uuid::Uuid;

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ProjectModel {
    pub id: Uuid,
    pub name: String,
    pub created_at: String,
}

// Input type for creating a project (no id, created_at is auto-generated by DB)
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct NewProject {
    pub name: String,
}